export const SET_LOGIN_SUCCESS = "SET_LOGIN_SUCCESS";
export const SET_PRODUCT_LIST_VIEW = "SET_PRODUCT_LIST_VIEW";
export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
